services:
  db:
    image: postgres:16
    container_name: d2c_postgres
    environment:
      POSTGRES_DB: d2c_pulse_tracker
      POSTGRES_USER: d2c_user
      POSTGRES_PASSWORD: d2c_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: d2c_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
