# Generated by Django 6.0.6 on 2026-07-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('vendor', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
