# Generated by Django 6.0.6 on 2026-07-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cluster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
